### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jadbox** [andreaferretti/rxnim#1]
It would be awesome to see a few examples (or unit tests). :)

**Comment by andreaferretti** [comment]
Well... RIght now it is just a little experiment - in fact it is not even on nimble yet. I wonder how you found it :-)

If it becomes something more serious, I will certainly document it properly

**Comment by jadbox** [comment]
My two favorite things in the world are Nim and Rx... so it was ineviditable for me to find this. I think it was on Twitter though (maybe @Reactivex) :)

**Comment by andreaferretti** [comment]
I had not told anyone, but it seems it was tweeted without anyway :-)

In any case, would you be interested in helping? I am a novice with RX, and this is more an exercise to learn it than anything. If you would like to collaborate, I can share some words about what is there and then you can tell me what you think. The Rx guys seem to have given a lot of thought on how to design the API, so implementing it should be rather straightforward - although certainly not trivial

**Comment by jadbox** [comment]
I really wish I had free time (or even open weekend). In a couple weeks though, I'll loop back when I have more time to help in what ways I can. :]
